# PostgreSQL versions 7.4 - 8.1
#
# Get the C bindings:
#   gem install postgres
# or use the pure-Ruby bindings on Windows:
#   gem install postgres-pr
development:
  adapter: postgresql
  database: urbanaut_dev
  username: urbanaut_clickt 
  password: YUDNS9WLQBSV

test:
  adapter: postgresql
  database: urbanaut_test
  username: urbanaut_clickt
  password: YUDNS9WLQBSV

production:
  adapter: postgresql
  database: urbanaut_product
  username: urbanaut_clickt 
  password: YUDNS9WLQBSV
